### ISSUE TITLE
Error generating changelog

### ISSUE THREAD

**Issue by rderoldan1** [lab2023/katip#17]
``` bash
% katip  
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/katip-1.1.0/bin/katip:66:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
```

I think is probably because I has some spanish characters in my commits (á, ú, í)

**Comment by baygunm** [comment]
Thanks for opening issue. If you provide one or more sample commit notes, we can test and resolve this bug.

**Comment by baygunm** [comment]
Thanks for opening issue. If you provide one or more sample commit notes,
we can test and resolve this bug.

22 Aðustos 2013 Perþembe tarihinde Ruben Espinosa adlý kullanýcý þöyle
yazdý:

> % katip
> /usr/local/rvm/gems/ruby-1.9.3-p392/gems/katip-1.1.0/bin/katip:66:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
> 
> I think is probably because I has some spanish characters in my commits
> (á, ú, í)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/kebab-project/katip/issues/17
> .

## 

Saygýlarýmla,
Ýyi çalýþmalar

Murat Kemal BAYGÜN
lab2023 - internet teknolojileri
www.lab2023.com

Adres: Pamukkale Üniversitesi Teknoloji Geliþtirme Bölgesi
Kuluçka Merkezi ve Ýdari Binasý B-Blok Z13 Kýnýklý / Denizli / TÜRKÝYE
Telefon: +90 258 215 50 10 -  E-posta: info@lab2023.com

**Comment by rderoldan1** [comment]
Look a couple of my commits:

```
corrección actulizando beneficiario
corrección en validacion beneficiarios
error obteniendo el país
ciudad y país en sesiones
```

In some of my spanish projects I had to tell ruby for use utf-8 and it works for me, example

``` ruby
# encodign: utf-8
class Myclass
  ..
end
```

**Comment by rderoldan1** [comment]
If I run the command specifying the encoding it works

``` bash
% LANG=utf-8 katip
Create CHANGELOG.md
```

**Comment by onurozgurozkan** [comment]
@rderoldan1 thanks for feedback.

**Comment by baygunm** [comment]
Thanks for the update.

**Comment by baygunm** [comment]
@rderoldan1 
Will you send the previous value of LANG variable before setting?

``` sh
%echo $LANG
```

I'm looking forward for your result

**Comment by rderoldan1** [comment]
The LANG command doesn't return anything, the error is related with non US_ASCII character, because in my commits I use UTF-8 characters
Ruben Espinosa Roldan
rderoldan1@gmail.com

**Comment by baygunm** [comment]
Thanks Ruben
But we cannot regenerate the bug with your sample comments, even with LANG is not set.
So maybe we will be asking you to test some development code and send the result if it works.
If ok we will send you the gem in development after working on some possible solutions.

By this time you can continue using gem with your workaround (Setting LANG variable with utf-8 and running katip)

``` bash
% LANG=utf-8 katip
Create CHANGELOG.md
```

**Comment by rderoldan1** [comment]
I'm using your gem as you tell me, probably the issue is reflected in this commit
     correcciÃ³n en presiciÃ³n decimales

The output in the changelog.md is 

6da3c13 correcciÃ³n en presiciÃ³n decimales (Ruben Espinosa)
