### ISSUE TITLE
katip:66:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by onurozgurozkan** [lab2023/katip#22]
![screen shot 2013-09-05 at 10 56 55 am](https://f.cloud.github.com/assets/248897/1086564/e000de4a-1600-11e3-9d09-3dfdc1ebdb7b.png)

**Comment by baygunm** [comment]
Working on it.
Thanks

**Comment by baygunm** [comment]
Duplicate #17, Already solved by #18
