### ISSUE TITLE
Add ability to specify tag range for changelog

### ISSUE THREAD

**Issue by jabclab** [lab2023/katip#28]
Hi there,

Really liking the tool :smile:

One thing that would make it more useful for me would be the ability to specify a tag range for the changelog. At present my app contains a lot of tags, some of which I don't need in the changelog anymore.

Something like:

```
$ katip my_changelog.md --from=0.2.1 --to=0.2.9
```

**Comment by onurozgurozkan** [comment]
:+1:

**Comment by baygunm** [comment]
:+1:

**Comment by tayfunoziserikan** [comment]
I like this idea. :+1:

**Comment by marjinal1st** [comment]
Working on the feature right now :+1:

**Comment by baygunm** [comment]
Released with 1.5.1.
Thanks for suggestion and contribution

**Comment by jabclab** [comment]
Awesome, thanks guys @marjinal1st @baygunm
